spring:
  datasource:
    url: ${MYSQLDB_URL}
    username: ${MYSQLDB_USER}
    password: ${MYSQLDB_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${SPRING_DOCKER_PORT}
